strictDepBuilds: true
allowBuilds:
  "@vercel/speed-insights": true
  "esbuild": true
  "@prisma/engines": false
  "prisma": false
  "sharp": false
  "msgpackr-extract": false
  "unrs-resolver": false
  "core-js-pure": false
overrides:
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  "undici@>=4.5.0 <5.28.5": ">=5.28.5"
  "undici@<6.23.0": ">=6.23.0"
  "undici@<5.29.0": ">=5.29.0"
  "tar@<7.5.8": ">=7.5.8"
  "minimatch@>=10.0.0 <10.2.1": ">=10.2.1"
  "minimatch@>=10.0.0 <10.2.3": ">=10.2.3"
  "ajv@>=7.0.0-alpha.0 <8.18.0": ">=8.18.0"
  "tar@<=7.5.9": ">=7.5.10"
  "tar@<=7.5.10": ">=7.5.11"
  "undici@<6.24.0": ">=6.24.0"
  "smol-toml@<1.6.1": ">=1.6.1"
  "srvx@<0.11.13": ">=0.11.13"
  "path-to-regexp@>=8.0.0 <8.4.0": ">=8.4.0"
  "vite@>=7.0.0 <=7.3.1": ">=7.3.2"
  "vite@>=7.1.0 <=7.3.1": ">=7.3.2"
  "@hono/node-server@<1.19.13": ">=1.19.13"
  "postcss@<8.5.10": ">=8.5.10"
  "vercel@>=50.16.0 <=52.0.0": ">=52.0.1"
  "@tootallnate/once@<2.0.1": ">=2.0.1"
  "uuid@<11.1.1": ">=11.1.1"
  "esbuild@>=0.27.3 <0.28.1": ">=0.28.1"
  "form-data@>=4.0.0 <4.0.6": ">=4.0.6"
  "tar@<=7.5.15": ">=7.5.16"
  "vite@>=7.0.0 <=7.3.4": ">=7.3.5"
  "js-yaml@<=4.1.1": ">=4.2.0"
  "undici@>=7.23.0 <7.28.0": ">=7.28.0"
  "undici@>=7.0.0 <7.28.0": ">=7.28.0"
  "undici@<6.27.0": ">=6.27.0"
minimumReleaseAgeExclude:
  - '@vercel/backends@8.0.1'
  - '@vercel/build-utils@14.10.1'
  - '@vercel/cervel@0.1.65'
  - '@vercel/container@8.1.0'
  - '@vercel/elysia@8.0.1'
  - '@vercel/express@8.0.1'
  - '@vercel/fastify@8.0.1'
  - '@vercel/gatsby-plugin-vercel-builder@2.2.57'
  - '@vercel/go@11.0.1'
  - '@vercel/h3@8.0.1'
  - '@vercel/hono@8.0.1'
  - '@vercel/hydrogen@9.0.1'
  - '@vercel/koa@8.0.1'
  - '@vercel/nestjs@8.0.1'
  - '@vercel/next@12.0.1'
  - '@vercel/node@13.0.1'
  - '@vercel/python@14.1.0'
  - '@vercel/redwood@10.0.1'
  - '@vercel/remix-builder@13.0.1'
  - '@vercel/ruby@10.0.1'
  - '@vercel/rust@9.0.1'
  - '@vercel/static-build@10.0.1'
  - '@vercel/vc-native-darwin-arm64@59.17.0'
  - '@vercel/vc-native-darwin-x64@59.17.0'
  - '@vercel/vc-native-linux-arm64@59.17.0'
  - '@vercel/vc-native-linux-x64@59.17.0'
  - vercel@59.17.0
